"""Deterministic renderer for the project's chosen citation style.

The writer (`app.services.writing`) and the claim verifier
(`app.services.fulltext.extract_claims_from_document`) both stay author-year, unchanged
by this module. What the author chose in `project.citation_style` (APA, Chicago, MLA,
Harvard, IEEE, Vancouver or a custom label, treated as APA) is applied only here, at two
points: export (`app.api.drafts.export_draft`) and paper chat
(`app.api.paper_chat.chat_with_papers`). Reference entries are built from the project's
own paper metadata (`authors`, `year`, `title`, `journal_name`, `doi`); nothing is
generated by a model.

Two entry points share one core:

* `render_document` walks a Tiptap draft document, using the paragraph's own
  `citationLinks` (the map the writer module produced) to find each citation's position;
* `render_answer` walks a plain-text chat answer, using `fulltext.citation_extents` and
  `fulltext.build_paper_lookup` -- the same span reconstruction and paper lookup the
  claim verifier itself uses, so a rendered number and a verification verdict always
  name the same paper.

Both reduce to the same citation occurrence shape, `(start, end, keys)` within one block
of text: IEEE and Vancouver replace each occurrence with its assigned number(s) in
first-appearance order; every other style (including `custom`) leaves the text
untouched. A reference list, built only from papers actually cited, is always appended
when there is at least one.

Pure and synchronous throughout: no network call, no database session, no write-back to
the draft it was given.
"""

from __future__ import annotations

import copy
import re
from dataclasses import dataclass, field
from typing import Any, Iterator

from pydantic import BaseModel, Field

from app.services.citation_audit import NAME_PARTICLES, citation_spans
from app.services.fulltext import (
    REFERENCE_LIST_HEADING_RE,
    build_paper_lookup,
    citation_extents,
)

#: Styles whose in-text citations are replaced with numbers. Matched case-insensitively
#: against `project.citation_style`; every other value, including `custom`, is rendered
#: as APA-form author-year.
_NUMBERED_STYLES = frozenset({"ieee", "vancouver"})


class RenderedDocument(BaseModel):
    """What `render_document` returns: the rendered Tiptap document (a deep copy, the
    input is never mutated) plus a summary of how many citations were found, rendered
    and left unresolved."""

    content: dict | None = None
    references: list[str] = Field(default_factory=list)
    numbered: bool = False
    found: int = 0
    rendered: int = 0
    unresolved: list[str] = Field(default_factory=list)


class RenderedText(BaseModel):
    """What `render_answer` returns: the rendered markdown answer plus the same summary
    `RenderedDocument` carries."""

    text: str = ""
    references: list[str] = Field(default_factory=list)
    numbered: bool = False
    found: int = 0
    rendered: int = 0
    unresolved: list[str] = Field(default_factory=list)


def _style_key(style: str | None) -> str:
    return (style or "APA").strip().casefold()


def _is_numbered(style: str | None) -> bool:
    return _style_key(style) in _NUMBERED_STYLES


def _normalize_ws(text: str) -> str:
    """Collapse whitespace runs to one space (mirrors
    `app.services.fulltext._doc_normalize_ws`; kept as a separate one-line function here
    rather than imported, since this module takes only three delegations from
    `app.services.fulltext`)."""
    return " ".join((text or "").split())


def _find_all_spans(text: str, snippet: str) -> list[tuple[int, int]]:
    """Every verbatim, non-overlapping ``(start, end)`` occurrence of *snippet* in
    *text*, left to right (mirrors `app.services.fulltext._find_all_spans`; kept as a
    separate function for the same reason as `_normalize_ws` above)."""
    if not snippet:
        return []
    spans: list[tuple[int, int]] = []
    cursor = 0
    while True:
        start = text.find(snippet, cursor)
        if start == -1:
            break
        spans.append((start, start + len(snippet)))
        cursor = start + len(snippet)
    return spans


def _meta(paper: Any, name: str) -> Any:
    """One field off *paper*, whether it is an ORM `Paper`, a SQLAlchemy result row (what
    paper chat holds) or a plain dict."""
    if isinstance(paper, dict):
        return paper.get(name)
    return getattr(paper, name, None)


def _author_display_names(paper: Any) -> list[str]:
    names: list[str] = []
    for author in _meta(paper, "authors") or []:
        if isinstance(author, dict):
            name = author.get("name") or author.get("family") or ""
        else:
            name = str(author or "")
        if name:
            names.append(name)
    return names


def _split_name(raw: str) -> tuple[str, str]:
    """(family, given) from one author name: split at the first
    comma when there is one ("Smith, Jane Q." -> ("Smith", "Jane Q.")); otherwise at the
    last whitespace token, plus any directly preceding lower-case particle from
    `citation_audit.NAME_PARTICLES` ("Teun van Dijk" -> ("van Dijk", "Teun"))."""
    raw = (raw or "").strip()
    if not raw:
        return "", ""
    if "," in raw:
        family, _, given = raw.partition(",")
        return family.strip(), given.strip()
    tokens = raw.split()
    if len(tokens) <= 1:
        return (tokens[0] if tokens else ""), ""
    split_at = len(tokens) - 1
    if split_at >= 1 and tokens[split_at - 1] in NAME_PARTICLES:
        split_at -= 1
    return " ".join(tokens[split_at:]), " ".join(tokens[:split_at])


def _initials(given: str, *, sep: str = " ", period: bool = True) -> str:
    letters = [token[0].upper() for token in given.split() if token]
    if period:
        letters = [f"{letter}." for letter in letters]
    return sep.join(letters)


def _author_apa(family: str, given: str) -> str:
    initials = _initials(given)
    return f"{family}, {initials}" if initials else family


def _author_full_first(family: str, given: str) -> str:
    """'Family, Given' -- Chicago's and MLA's first-author form."""
    return f"{family}, {given}" if given else family


def _author_given_family(family: str, given: str) -> str:
    """'Given Family' -- Chicago's and MLA's subsequent-author form."""
    return f"{given} {family}".strip() if given else family


def _author_harvard(family: str, given: str) -> str:
    initials = _initials(given, sep="")
    return f"{family}, {initials}" if initials else family


def _author_ieee(family: str, given: str) -> str:
    initials = _initials(given)
    return f"{initials} {family}".strip() if initials else family


def _author_vancouver(family: str, given: str) -> str:
    initials = _initials(given, sep="", period=False)
    return f"{family} {initials}".strip() if initials else family


def _join_authors(formatted: list[str], connector: str, comma_before_connector: bool) -> str:
    if not formatted:
        return ""
    if len(formatted) == 1:
        return formatted[0]
    sep = f", {connector} " if comma_before_connector else f" {connector} "
    return ", ".join(formatted[:-1]) + sep + formatted[-1]


Names = list[tuple[str, str]]


def _format_apa(
    authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    authors_str = _join_authors([_author_apa(f, g) for f, g in authors], "&", True)
    entry = f"{authors_str} ({year or 'n.d.'}). {title}."
    if journal:
        entry += f" {journal}."
    if doi:
        entry += f" https://doi.org/{doi}"
    return entry


def _format_chicago(
    authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    formatted = [
        _author_full_first(f, g) if i == 0 else _author_given_family(f, g)
        for i, (f, g) in enumerate(authors)
    ]
    authors_str = _join_authors(formatted, "and", True)
    entry = f'{authors_str}. {year or "n.d."}. "{title}."'
    if journal:
        entry += f" {journal}."
    if doi:
        entry += f" https://doi.org/{doi}"
    return entry


def _format_mla(
    authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    if len(authors) >= 3:
        family, given = authors[0]
        authors_str = f"{_author_full_first(family, given)}, et al"
    else:
        formatted = [
            _author_full_first(f, g) if i == 0 else _author_given_family(f, g)
            for i, (f, g) in enumerate(authors)
        ]
        authors_str = _join_authors(formatted, "and", True)
    doi_part = f"https://doi.org/{doi}" if doi else None
    trailing = [part for part in (journal, year or "n.d.", doi_part) if part]
    entry = f'{authors_str}. "{title}."'
    if trailing:
        entry += " " + ", ".join(trailing) + "."
    return entry


def _format_harvard(
    authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    authors_str = _join_authors([_author_harvard(f, g) for f, g in authors], "and", False)
    entry = f"{authors_str} ({year or 'n.d.'}) '{title}'"
    entry += f", {journal}." if journal else "."
    if doi:
        entry += f" Available at: https://doi.org/{doi}"
    return entry


def _format_ieee(
    number: int, authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    authors_str = _join_authors([_author_ieee(f, g) for f, g in authors], "and", False)
    entry = f'[{number}] {authors_str}, "{title},"'
    trailing = [part for part in (journal, year) if part]
    entry += (" " + ", ".join(trailing) + ".") if trailing else "."
    if doi:
        entry += f" doi: {doi}."
    return entry


def _format_vancouver(
    number: int, authors: Names, title: str, journal: str | None, year: str | None, doi: str | None
) -> str:
    authors_str = ", ".join(_author_vancouver(f, g) for f, g in authors)
    entry = f"{number}. {authors_str}. {title}."
    if journal:
        entry += f" {journal}."
    if year:
        entry += f" {year}."
    if doi:
        entry += f" doi:{doi}."
    return entry


def _format_entry(number: int | None, paper: Any, style: str) -> str:
    """One reference-list entry for *paper*, in *style*. Only
    `authors`, `year`, `title`, `journal_name` and `doi` are read; a missing element is
    omitted, never invented."""
    authors = [_split_name(name) for name in _author_display_names(paper)]
    title = _meta(paper, "title") or ""
    journal = _meta(paper, "journal_name") or None
    raw_year = _meta(paper, "year")
    year = str(raw_year) if raw_year else None
    doi = _meta(paper, "doi") or None

    key = _style_key(style)
    if key == "chicago":
        return _format_chicago(authors, title, journal, year, doi)
    if key == "mla":
        return _format_mla(authors, title, journal, year, doi)
    if key == "harvard":
        return _format_harvard(authors, title, journal, year, doi)
    if key == "ieee":
        return _format_ieee(number or 1, authors, title, journal, year, doi)
    if key == "vancouver":
        return _format_vancouver(number or 1, authors, title, journal, year, doi)
    return _format_apa(authors, title, journal, year, doi)  # apa, custom, anything else


def _sort_key(paper: Any) -> tuple[str, int, str]:
    names = _author_display_names(paper)
    family = _split_name(names[0])[0] if names else ""
    return (family.casefold(), _meta(paper, "year") or 0, (_meta(paper, "title") or "").casefold())


def _build_references(
    cited_keys_in_order: list[str], paper_lookup: dict, style: str, numbered: bool
) -> list[str]:
    """Reference-list entries for the papers actually cited, deduplicated, in
    first-appearance order for a numbered style or sorted by family/year/title
    otherwise."""
    seen: list[str] = []
    for key in cited_keys_in_order:
        if key not in seen:
            seen.append(key)
    if not seen:
        return []
    if numbered:
        return [_format_entry(i, paper_lookup[key], style) for i, key in enumerate(seen, start=1)]
    ordered = sorted(seen, key=lambda k: _sort_key(paper_lookup[k]))
    return [_format_entry(None, paper_lookup[key], style) for key in ordered]


@dataclass
class _Occurrence:
    """One citation occurrence: `(start, end, keys)` within one block of text.
    ``rendered`` is set only for a lone occurrence built straight from
    `fulltext.citation_extents`: the audit's own,
    already-balanced form of this one member, held in reserve for when ``start:end``
    itself is not balanced -- true of a semicolon-group member whose neighbour is
    keyless, which blocks the merge that would otherwise widen the slice back to the
    whole, balanced group. Left empty by a
    merge and by a link-covered occurrence, both of which keep a balanced slice already."""

    start: int
    end: int
    keys: list[str] = field(default_factory=list)
    rendered: str = ""


def _resolvable_keys(occurrence: _Occurrence, paper_lookup: dict) -> list[str]:
    return [key for key in occurrence.keys if key in paper_lookup]


def _is_balanced(text: str) -> bool:
    """True when every ``(``/``)`` and ``[``/``]`` in *text* is matched, in order
    (mirrors `app.services.fulltext._is_bracket_balanced`; kept as a separate function
    here for the same reason as `_normalize_ws` above)."""
    depth_paren = depth_bracket = 0
    for character in text:
        if character == "(":
            depth_paren += 1
        elif character == ")":
            depth_paren -= 1
            if depth_paren < 0:
                return False
        elif character == "[":
            depth_bracket += 1
        elif character == "]":
            depth_bracket -= 1
            if depth_bracket < 0:
                return False
    return depth_paren == 0 and depth_bracket == 0


def _balanced_or(raw: str, fallback: str) -> str:
    """*raw* when it is bracket-balanced, and *fallback* otherwise. Shared by
    `_unresolved_text`, which has a source
    position to slice *raw* from, and the stale-text path in `_draft_occurrences`, which
    does not. Nothing is ever deleted by this -- only the string a human is shown."""
    return raw if _is_balanced(raw) else (fallback or raw)


def _trim_to_balanced(text: str) -> str:
    """*text* with characters trimmed from the right until what remains is
    bracket-balanced, or *text* itself if trimming would empty it out first. The only
    fallback available for
    a stale link's own ``citation_text``, which -- unlike an occurrence built from
    `citation_extents` -- carries no position in the paragraph to look an audit-rendered
    form up by."""
    trimmed = text
    while trimmed and not _is_balanced(trimmed):
        trimmed = trimmed[:-1]
    return trimmed or text


def _unresolved_text(text: str, occurrence: _Occurrence) -> str:
    """The text `unresolved` reports for *occurrence*: its raw slice when that is
    bracket-balanced, and its own audit-rendered form otherwise. Nothing is ever
    deleted by this -- only the string a human is shown."""
    raw = text[occurrence.start : occurrence.end]
    return _balanced_or(raw, occurrence.rendered)


def _fully_resolved(occurrence: _Occurrence, resolved: list[str]) -> bool:
    """Whether every key *occurrence* carries is resolved. A merged citation with one
    member absent from the library is rendered
    only when *all* of its members resolve; otherwise the whole occurrence is left
    exactly as written and reported in `unresolved`, rather than silently naming only
    the source(s) that did resolve."""
    return bool(resolved) and len(resolved) == len(occurrence.keys)


_SEMICOLON_GAP_RE = re.compile(r"^\s*;\s*$")


def _merge_semicolon_adjacent(text: str, occurrences: list[_Occurrence]) -> list[_Occurrence]:
    """Two adjacent occurrences separated only by ``;`` and whitespace merge into one,
    carrying both occurrences' keys in order: the shape
    `fulltext._audit_span_units` reconstructs a semicolon-delimited group into, one
    member per unit ("(Storch, 2018; Lee, 2019)" is two units before this step), so a
    single group is numbered and replaced as the one citation it renders as.

    Neither side of a merge may be keyless.
    A citation no link covers reaches here with ``keys == []`` (`_draft_occurrences`'s
    own fallback for a citation the writer's map never touched); merging it into an
    adjacent, resolvable occurrence made the merged occurrence's key count equal its
    resolved count by accident, so `_fully_resolved` accepted it and replaced the whole
    merged range -- keyless member's text included -- with the resolvable member's
    number alone. A keyless occurrence now always stays on its own, exactly as if it had
    no semicolon-adjacent neighbour at all."""
    if not occurrences:
        return []
    ordered = sorted(occurrences, key=lambda o: (o.start, o.end))
    merged: list[_Occurrence] = [ordered[0]]
    for occurrence in ordered[1:]:
        last = merged[-1]
        can_merge = (
            last.keys
            and occurrence.keys
            and _SEMICOLON_GAP_RE.match(text[last.end : occurrence.start])
        )
        if can_merge:
            merged[-1] = _Occurrence(
                start=last.start, end=occurrence.end, keys=last.keys + occurrence.keys
            )
        else:
            merged.append(occurrence)
    return merged


def _assign_numbers(blocks: list[list[_Occurrence]], paper_lookup: dict) -> dict[str, int]:
    """key -> number, in first-appearance order: blocks in document order, occurrences by
    start offset, keys within an occurrence in their own order.
    An occurrence that will be left unresolved (one of its keys is not in the library)
    reserves no number for any of its keys, so a
    citation rendered nowhere never leaves a gap in the numbering."""
    numbers: dict[str, int] = {}
    for occurrences in blocks:
        for occurrence in sorted(occurrences, key=lambda o: (o.start, o.end)):
            resolved = _resolvable_keys(occurrence, paper_lookup)
            if not _fully_resolved(occurrence, resolved):
                continue
            for key in resolved:
                if key not in numbers:
                    numbers[key] = len(numbers) + 1
    return numbers


def _format_numbers(numbers: list[int], style_key: str) -> str:
    if style_key == "vancouver":
        return "[" + ", ".join(str(n) for n in numbers) + "]"
    return ", ".join(f"[{n}]" for n in numbers)  # ieee


def _narrative_replace_range(text: str, occurrence: _Occurrence) -> tuple[int, int]:
    """The range actually replaced for *occurrence*: a narrative
    citation keeps its author, only the parenthesised year onward is replaced ("Smith et
    al. (2020) showed" -> "Smith et al. [1] showed"); a purely parenthetical citation is
    replaced whole ("(Smith, 2020)" -> "[1]")."""
    snippet = text[occurrence.start : occurrence.end]
    paren = snippet.find("(")
    if paren > 0:
        return occurrence.start + paren, occurrence.end
    return occurrence.start, occurrence.end


# --------------------------------------------------------------------------------------
# Chat path: fulltext.citation_extents + fulltext.build_paper_lookup.
# The chat answer is a single block of plain text.
# --------------------------------------------------------------------------------------


#: A markdown heading line ("## References", "# Bibliography", ...): matched the same
#: way `_drop_existing_reference_section` matches a Tiptap heading node, just applied to
#: a `#`-prefixed line of plain text instead of a node's own text.
_MARKDOWN_HEADING_LINE_RE = re.compile(r"(?m)^#{1,6}[ \t]+(.+?)[ \t]*$")


def _strip_trailing_reference_section(text: str) -> str:
    """Drop a reference-list heading and the block up to the next heading from *text*.
    Chat rule 5 tells the model not to write its own references section; when it
    does anyway, this keeps the answer to one, ours -- exactly what
    `_drop_existing_reference_section` already does for a draft document, including
    keeping whatever follows the next heading, rather than dropping
    everything to the end of the answer, which would delete a genuine section (such as
    "## Limitations") that happened to come after the model's own reference list."""
    matches = list(_MARKDOWN_HEADING_LINE_RE.finditer(text))
    for index, match in enumerate(matches):
        if not REFERENCE_LIST_HEADING_RE.match(match.group(1).strip()):
            continue
        if index + 1 < len(matches):
            following = text[matches[index + 1].start() :]
            return (text[: match.start()].rstrip() + "\n\n" + following).rstrip()
        return text[: match.start()].rstrip()
    return text


def _chat_occurrences(text: str) -> list[_Occurrence]:
    spans = citation_spans(text)
    occurrences: list[_Occurrence] = []
    for start, end, rendered in citation_extents(text):
        keys: list[str] = []
        for position, surname, year, _label in spans:
            if start <= position < end and year is not None:
                keys = [f"{surname.split()[-1].lower()}_{year}"]
                break
        occurrences.append(_Occurrence(start=start, end=end, keys=keys, rendered=rendered))
    return occurrences


def render_answer(text: str, papers: list, style: str) -> RenderedText:
    """Render *text* (a paper-chat answer, author-year in text) in the project's chosen
    *style*. Author-year styles return the text unchanged, plus
    a references section built from *papers*' own metadata; IEEE and Vancouver also
    replace each citation with its assigned number(s)."""
    numbered = _is_numbered(style)
    if not text or not papers:
        return RenderedText(text=text or "", numbered=numbered)

    paper_lookup = build_paper_lookup(list(papers))
    if not paper_lookup:
        return RenderedText(text=text, numbered=numbered)

    style_key = _style_key(style)
    occurrences = _merge_semicolon_adjacent(text, _chat_occurrences(text))
    found = len(occurrences)
    numbers = _assign_numbers([occurrences], paper_lookup) if numbered else {}

    cited_keys_in_order: list[str] = []
    unresolved: list[str] = []
    edits: list[tuple[int, int, str]] = []
    rendered_count = 0

    for occurrence in sorted(occurrences, key=lambda o: (o.start, o.end)):
        resolved = _resolvable_keys(occurrence, paper_lookup)
        if not _fully_resolved(occurrence, resolved):
            unresolved.append(_unresolved_text(text, occurrence))
            continue
        for key in resolved:
            if key not in cited_keys_in_order:
                cited_keys_in_order.append(key)
        if not numbered:
            continue
        nums = [numbers[key] for key in resolved]
        start, end = _narrative_replace_range(text, occurrence)
        edits.append((start, end, _format_numbers(nums, style_key)))
        rendered_count += 1

    for start, end, replacement in sorted(edits, key=lambda e: e[0], reverse=True):
        text = text[:start] + replacement + text[end:]

    references = _build_references(cited_keys_in_order, paper_lookup, style, numbered)
    if references:
        text = _strip_trailing_reference_section(text)
        text = text.rstrip() + "\n\n## References\n" + "\n".join(references)

    return RenderedText(
        text=text,
        references=references,
        numbered=numbered,
        found=found,
        rendered=rendered_count,
        unresolved=unresolved,
    )


# --------------------------------------------------------------------------------------
# Draft path: the paragraph's own citationLinks. Duplicated
# here, in miniature, rather than imported: `fulltext`'s own paragraph walk
# (`_iter_paragraph_nodes`, `_CONTAINER_NODE_TYPES`) is read-only text extraction, while
# this module also needs each citation's own text-node offsets to mutate a single node in
# place, so it keeps its own copy of the recursion rule instead of half-reusing fulltext's.
# --------------------------------------------------------------------------------------

#: Node types whose own ``content`` holds further nodes to walk into, so a citation
#: inside a bulleted list or a blockquote is found exactly like a top-level paragraph
#: (mirrors `fulltext._CONTAINER_NODE_TYPES`).
_CONTAINER_NODE_TYPES = frozenset({"bulletList", "orderedList", "listItem", "blockquote"})


def _iter_paragraph_nodes(nodes: list[dict]) -> Iterator[dict]:
    for node in nodes:
        if not isinstance(node, dict):
            continue
        node_type = node.get("type")
        if node_type == "paragraph":
            yield node
        elif node_type in _CONTAINER_NODE_TYPES:
            yield from _iter_paragraph_nodes(
                [n for n in (node.get("content") or []) if isinstance(n, dict)]
            )


def _node_text(node: dict) -> str:
    """Plain text of a heading or paragraph node's own direct text children (no
    recursion: a heading or paragraph's content is inline nodes, not further blocks)."""
    return "".join(
        c.get("text") or ""
        for c in (node.get("content") or [])
        if isinstance(c, dict) and c.get("type") == "text"
    )


def _paragraph_text_nodes(node: dict) -> list[dict]:
    return [
        c for c in (node.get("content") or []) if isinstance(c, dict) and c.get("type") == "text"
    ]


def _node_offsets(text_nodes: list[dict]) -> list[tuple[int, int]]:
    offsets: list[tuple[int, int]] = []
    cursor = 0
    for node in text_nodes:
        length = len(node.get("text") or "")
        offsets.append((cursor, cursor + length))
        cursor += length
    return offsets


def _containing_node_index(offsets: list[tuple[int, int]], start: int, end: int) -> int | None:
    for index, (node_start, node_end) in enumerate(offsets):
        if node_start <= start and end <= node_end:
            return index
    return None


def _drop_existing_reference_section(nodes: list[dict]) -> list[dict]:
    """Drop an existing reference section -- a heading matching
    `fulltext.REFERENCE_LIST_HEADING_RE`, and everything up to the next heading -- so
    export never shows two reference lists."""
    for index, node in enumerate(nodes):
        if not isinstance(node, dict) or node.get("type") != "heading":
            continue
        if not REFERENCE_LIST_HEADING_RE.match(_node_text(node).strip()):
            continue
        end = len(nodes)
        for later in range(index + 1, len(nodes)):
            if isinstance(nodes[later], dict) and nodes[later].get("type") == "heading":
                end = later
                break
        return nodes[:index] + nodes[end:]
    return nodes


def _draft_occurrences(
    paragraph_text: str, links: list[dict]
) -> tuple[list[_Occurrence], list[str]]:
    """Occurrences from one paragraph's own ``citationLinks``, plus the bare
    ``citation_text`` of any link whose text no longer occurs verbatim, plus a citation
    `fulltext.citation_extents` finds that no link covers at all: every
    citation in a draft written before citation links existed, and any citation typed
    into the editor after generation. A link counts only while its own ``sentence``
    still occurs in the paragraph, whitespace normalised; a link whose sentence has gone
    stale is ignored outright, exactly as `fulltext.extract_claims_from_document` ignores
    it. A citation_text shared by two links (rendered twice) is allocated to its own
    occurrence left to right.

    A `citation_extents` span already claimed by an occurrence above is skipped by
    position, not by text: comparing
    normalised text instead, keyed on every link's own ``citation_text``, made a second,
    distinct occurrence of the same wording (a source cited twice in one paragraph, only
    the first citation linked) look "already accounted for" and drop it silently. Only a
    stale link's own text is still tracked by text, since a stale link has no position at
    all to compare by, and the whitespace it went stale over (a link's ``citation_text``
    normalised-equal to the paragraph's own spelling, but not verbatim) is exactly the
    shape a position comparison cannot catch.

    Every occurrence built here carries ``rendered``, the covering `citation_extents`
    span's own already-balanced text: a link-derived occurrence gets it from the extent
    overlapping its own
    ``start``/``end``. A stale text has no position to look an extent up by at all, so it
    is balance-checked against `_trim_to_balanced` instead, which needs none: the one
    shape a `citation_text` has been seen to fail balance in is one bracket past the
    citation's own close, from an enclosing parenthetical the model's own text ran into,
    and trimming from the right recovers exactly that with no audit lookup required.
    Neither path changes which citation resolves; both only give `render_document`'s
    ``unresolved`` a string that is always bracket-balanced, matching what
    `fulltext.extract_claims_from_document` already reports for the same citation."""
    paragraph_norm = _normalize_ws(paragraph_text)
    occurrences: list[_Occurrence] = []
    stale_texts: list[str] = []
    stale_norm_texts: set[str] = set()
    spans_cache: dict[str, list[tuple[int, int]]] = {}
    next_index: dict[str, int] = {}
    extents = citation_extents(paragraph_text)

    def _covering_extent_text(start: int, end: int) -> str:
        for e_start, e_end, rendered in extents:
            if e_start < end and start < e_end:
                return rendered
        return ""

    for link in links:
        sentence_norm = _normalize_ws(link.get("sentence") or "")
        if not sentence_norm or sentence_norm not in paragraph_norm:
            continue  # stale: ignored, not counted at all
        citation_text = link.get("citation_text") or ""
        if citation_text not in spans_cache:
            spans_cache[citation_text] = _find_all_spans(paragraph_text, citation_text)
        spans = spans_cache[citation_text]
        index = next_index.get(citation_text, 0)
        if index >= len(spans):
            # citation_text no longer occurs verbatim: counted, unresolved, no position.
            stale_texts.append(_balanced_or(citation_text, _trim_to_balanced(citation_text)))
            stale_norm_texts.add(_normalize_ws(citation_text))
            continue
        next_index[citation_text] = index + 1
        start, end = spans[index]
        keys = [key for key in (link.get("keys") or []) if key]
        rendered = _covering_extent_text(start, end)
        occurrences.append(_Occurrence(start=start, end=end, keys=keys, rendered=rendered))

    for start, end, rendered in extents:
        if any(o.start < end and start < o.end for o in occurrences):
            continue  # already accounted for above, by position
        if _normalize_ws(rendered) in stale_norm_texts:
            continue  # the paragraph's own respelling of a link whose text went stale
        occurrences.append(_Occurrence(start=start, end=end, keys=[], rendered=rendered))

    return occurrences, stale_texts


def render_document(content: dict | None, papers: list, style: str) -> RenderedDocument:
    """Render *content* (a Tiptap draft document, author-year in text) in the project's
    chosen *style*. The input is deep-copied and never
    written back. Empty content, or a project with no papers, is returned unchanged with
    no reference section."""
    numbered = _is_numbered(style)
    if not isinstance(content, dict) or not papers:
        copied = copy.deepcopy(content) if isinstance(content, dict) else content
        return RenderedDocument(content=copied, numbered=numbered)

    paper_lookup = build_paper_lookup(list(papers))
    if not paper_lookup:
        return RenderedDocument(content=copy.deepcopy(content), numbered=numbered)

    style_key = _style_key(style)
    doc = copy.deepcopy(content)
    original_top_nodes = [n for n in (doc.get("content") or []) if isinstance(n, dict)]
    top_nodes = _drop_existing_reference_section(original_top_nodes)
    had_existing_reference_section = len(top_nodes) != len(original_top_nodes)

    found = 0
    unresolved: list[str] = []
    paragraphs: list[tuple[list[dict], list[tuple[int, int]], str, list[_Occurrence]]] = []

    for node in _iter_paragraph_nodes(top_nodes):
        text_nodes = _paragraph_text_nodes(node)
        paragraph_text = "".join(n.get("text") or "" for n in text_nodes)
        if not paragraph_text.strip():
            continue
        links = (node.get("attrs") or {}).get("citationLinks") or []
        raw_occurrences, stale_texts = _draft_occurrences(paragraph_text, links)
        occurrences = _merge_semicolon_adjacent(paragraph_text, raw_occurrences)
        found += len(occurrences) + len(stale_texts)
        unresolved.extend(stale_texts)
        paragraphs.append((text_nodes, _node_offsets(text_nodes), paragraph_text, occurrences))

    numbers = _assign_numbers([p[3] for p in paragraphs], paper_lookup) if numbered else {}

    cited_keys_in_order: list[str] = []
    rendered_count = 0

    for text_nodes, offsets, paragraph_text, occurrences in paragraphs:
        edits: dict[int, list[tuple[int, int, str]]] = {}
        for occurrence in occurrences:
            resolved = _resolvable_keys(occurrence, paper_lookup)
            if not _fully_resolved(occurrence, resolved):
                unresolved.append(_unresolved_text(paragraph_text, occurrence))
                continue
            for key in resolved:
                if key not in cited_keys_in_order:
                    cited_keys_in_order.append(key)
            if not numbered:
                continue
            start, end = _narrative_replace_range(paragraph_text, occurrence)
            node_index = _containing_node_index(offsets, start, end)
            if node_index is None:
                # An occurrence straddling two text nodes cannot be safely rewritten.
                unresolved.append(_unresolved_text(paragraph_text, occurrence))
                continue
            nums = [numbers[key] for key in resolved]
            local_start, local_end = start - offsets[node_index][0], end - offsets[node_index][0]
            edits.setdefault(node_index, []).append(
                (local_start, local_end, _format_numbers(nums, style_key))
            )
            rendered_count += 1

        for node_index, node_edits in edits.items():
            target = text_nodes[node_index]
            new_text = target.get("text") or ""
            for local_start, local_end, replacement in sorted(
                node_edits, key=lambda e: e[0], reverse=True
            ):
                new_text = new_text[:local_start] + replacement + new_text[local_end:]
            target["text"] = new_text

    references = _build_references(cited_keys_in_order, paper_lookup, style, numbered)
    # Whether to append the generated list and whether to
    # drop the document's own existing reference section are two different decisions.
    # Appending happens whenever there is a generated list to append -- a draft with no
    # reference section of its own (every draft the writer produces) must not export
    # with no list to read a rendered number against, just because one citation stayed
    # unresolved. Dropping the author's own existing section is the one that stays
    # gated on `unresolved`: it is safe only when the generated list is about to replace
    # it entirely, since a citation that resolved to a key absent from the library, or
    # one a link never covered at all, means the generated list covers only some of what
    # the renderer found, and dropping the author's section would silently delete their
    # entry for the rest.
    if references and (not had_existing_reference_section or not unresolved):
        heading_text = {"type": "text", "text": "References"}
        top_nodes.append(
            {"type": "heading", "attrs": {"level": 2}, "content": [heading_text]}
        )
        top_nodes.extend(
            {"type": "paragraph", "content": [{"type": "text", "text": entry}]}
            for entry in references
        )
        doc["content"] = top_nodes
    elif had_existing_reference_section:
        # The existing section (and everything after it) is kept, untouched, until
        # every citation the renderer found resolves.
        doc["content"] = original_top_nodes
    else:
        doc["content"] = top_nodes

    return RenderedDocument(
        content=doc,
        references=references,
        numbered=numbered,
        found=found,
        rendered=rendered_count,
        unresolved=unresolved,
    )
