"""add_paper_analyses_table_and_job_types

Revision ID: 09167dfe71e7
Revises: b1c2d3e4f5a6
Create Date: 2026-03-19 23:18:32.120472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09167dfe71e7'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new enum values to jobtype
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'quality_scoring'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'gap_analysis'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_analyses',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('methodology_rigor', sa.String(length=10), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theories_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_info', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_analyses_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_paper_analyses_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_analyses')),
    sa.UniqueConstraint('project_id', 'paper_id', name='uq_paper_analysis_project_paper')
    )
    op.create_index(op.f('ix_paper_analyses_paper_id'), 'paper_analyses', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_analyses_project_id'), 'paper_analyses', ['project_id'], unique=False)
    op.alter_column('drafts', 'paper_type',
               existing_type=postgresql.ENUM('literature_review', 'research_article', name='papertype'),
               nullable=False)
    op.alter_column('drafts', 'status',
               existing_type=postgresql.ENUM('draft', 'review', 'final', name='draftstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drafts', 'status',
               existing_type=postgresql.ENUM('draft', 'review', 'final', name='draftstatus'),
               nullable=True)
    op.alter_column('drafts', 'paper_type',
               existing_type=postgresql.ENUM('literature_review', 'research_article', name='papertype'),
               nullable=True)
    op.drop_index(op.f('ix_paper_analyses_project_id'), table_name='paper_analyses')
    op.drop_index(op.f('ix_paper_analyses_paper_id'), table_name='paper_analyses')
    op.drop_table('paper_analyses')
    # ### end Alembic commands ###
