"""add wos_journals table

Revision ID: 0c107d09a56f
Revises: a402f4995973
Create Date: 2026-03-21 09:36:01.836994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c107d09a56f'
down_revision: Union[str, None] = 'a402f4995973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wos_journals',
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('eissn', sa.String(length=20), nullable=True),
    sa.Column('journal_title', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wos_journals'))
    )
    op.create_index(op.f('ix_wos_journals_eissn'), 'wos_journals', ['eissn'], unique=False)
    op.create_index(op.f('ix_wos_journals_issn'), 'wos_journals', ['issn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wos_journals_issn'), table_name='wos_journals')
    op.drop_index(op.f('ix_wos_journals_eissn'), table_name='wos_journals')
    op.drop_table('wos_journals')
    # ### end Alembic commands ###
