"""add_research_design_and_data_collection_job_types

Revision ID: 0f26772e1ec1
Revises: 3629b9044065
Create Date: 2026-03-21 02:06:12.696159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f26772e1ec1'
down_revision: Union[str, None] = '3629b9044065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'research_design'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'data_collection'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
