"""add phase2g job types

Revision ID: 23015df767f4
Revises: e23e926f376f
Create Date: 2026-03-21 06:51:40.502093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23015df767f4'
down_revision: Union[str, None] = 'e23e926f376f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'deep_search'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'seed_expand'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'field_foundations'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'fulltext_acquire'")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'claim_verify'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
