"""add_citation_edges_table_and_graph_building_job_type

Revision ID: 3629b9044065
Revises: 09167dfe71e7
Create Date: 2026-03-21 00:57:53.667825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3629b9044065'
down_revision: Union[str, None] = '09167dfe71e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'graph_building'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_edges',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('citing_paper_id', sa.UUID(), nullable=False),
    sa.Column('cited_paper_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], name=op.f('fk_citation_edges_cited_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], name=op.f('fk_citation_edges_citing_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_citation_edges_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation_edges')),
    sa.UniqueConstraint('project_id', 'citing_paper_id', 'cited_paper_id', name='uq_citation_edge_project')
    )
    op.create_index(op.f('ix_citation_edges_project_id'), 'citation_edges', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_edges_project_id'), table_name='citation_edges')
    op.drop_table('citation_edges')
    # ### end Alembic commands ###
