"""add refined_topic and criteria to projects

Revision ID: 451270d9394a
Revises: f8a2b3c4d5e6
Create Date: 2026-03-23 00:51:58.304667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '451270d9394a'
down_revision: Union[str, None] = 'f8a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('refined_topic', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('inclusion_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('exclusion_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'exclusion_criteria')
    op.drop_column('projects', 'inclusion_criteria')
    op.drop_column('projects', 'refined_topic')
    # ### end Alembic commands ###
