"""add collection and categories to wos_journals

Revision ID: e47c10652a7a
Revises: 0c107d09a56f
Create Date: 2026-03-22 00:39:28.268533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47c10652a7a'
down_revision: Union[str, None] = '0c107d09a56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wos_journals', sa.Column('collection', sa.String(length=10), nullable=True))
    op.add_column('wos_journals', sa.Column('categories', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wos_journals', 'categories')
    op.drop_column('wos_journals', 'collection')
    # ### end Alembic commands ###
