from datetime import date
from typing import Literal

from pydantic import BaseModel, Field, model_validator

#: The stage at which a criterion
#: can be decided. "screener and verifier both in app optimized" -- a user writing criteria
#: in the app marks the ones that need the full paper, and the app flags rather than
#: discards those records at title-and-abstract stage (see the relevance screener guard).
CRITERION_STAGES: tuple[str, ...] = ("abstract", "full_text")


class SmartSearchRequest(BaseModel):
    query: str = Field(min_length=1, max_length=1000)
    inclusion_criteria: list[str] = Field(default_factory=list)
    exclusion_criteria: list[str] = Field(default_factory=list)
    #: Parallel to ``inclusion_criteria``/``exclusion_criteria``: each value "abstract" or
    #: "full_text", or the whole list empty (every criterion "abstract", the pre-S8 default).
    #: Additive and backward compatible: an older frontend build that never sends these
    #: fields gets the all-abstract default.
    inclusion_criteria_stages: list[str] = Field(default_factory=list)
    exclusion_criteria_stages: list[str] = Field(default_factory=list)
    wos_filter: Literal["auto", "on", "off"] = Field(
        default="auto",
        description=(
            "Stage 1 venue filter: 'on' requires the Web of Science journal list, 'off' "
            "skips it, 'auto' applies it only when the list has been imported."
        ),
    )
    #: One list of queries per round. When given, round ``r`` (1-indexed)
    #: uses ``queries_override[r - 1]`` instead of calling the query generator agent; a
    #: round beyond the given lists falls back to normal generation. ``None`` (the default)
    #: is the pre-existing behaviour: every round's queries are generated.
    queries_override: list[list[str]] | None = Field(
        default=None,
        description=(
            "One list of search queries per round, replayed instead of generated by the "
            "query generator agent for as many rounds as lists are given."
        ),
    )
    #: Forwarded to OpenAlex as a ``to_publication_date`` filter on every
    #: search call, so a replayed run sees the same corpus as of that date rather than
    #: whatever the index has grown to since. Recorded in the job result's ``criteria``.
    publication_date_max: date | None = Field(
        default=None,
        description=(
            "Only return papers published on or before this date, on every OpenAlex "
            "search call this job makes."
        ),
    )

    @model_validator(mode="after")
    def _validate_stage_lists(self) -> "SmartSearchRequest":
        for stages, criteria, name in (
            (self.inclusion_criteria_stages, self.inclusion_criteria, "inclusion_criteria_stages"),
            (self.exclusion_criteria_stages, self.exclusion_criteria, "exclusion_criteria_stages"),
        ):
            if not stages:
                continue
            if len(stages) != len(criteria):
                raise ValueError(
                    f"{name} must be empty or exactly parallel to its criteria list "
                    f"(got {len(stages)} for {len(criteria)} criteria)"
                )
            bad = [s for s in stages if s not in CRITERION_STAGES]
            if bad:
                raise ValueError(f"{name} values must be one of {CRITERION_STAGES}, got {bad!r}")
        return self

    @model_validator(mode="after")
    def _validate_queries_override(self) -> "SmartSearchRequest":
        if self.queries_override is not None:
            for i, round_queries in enumerate(self.queries_override, start=1):
                if not round_queries:
                    raise ValueError(f"queries_override round {i} must not be empty")
        return self
