"""Regenerate demo/SOURCES.md from the audit JSON files so every count is derived.

Usage: python demo/tools/build_sources.py

Inputs: demo/tools/{sources,verified,selected}.json and demo/seed_dois.json.
The prose is fixed here; the tables, lists and counts come from the files.
"""

from __future__ import annotations

import json
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
DEMO = TOOLS.parent
ACCESS_DATE = "2026-09-02"

NOT_SELECTED_REASONS = {
    "10.1017/s0261444824000478": (
        "review of the timing of corrective feedback in general (largely oral feedback), "
        "weak fit with the written-feedback protocol"
    ),
    "10.1016/j.asw.2018.11.001": (
        "third 2018 paper and fourth Assessing Writing paper; dropped for year/journal "
        "balance in favour of the 2023 Reading and Writing paper"
    ),
}


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _host(record: dict) -> str:
    url = record.get("checked_url") or ""
    return url.split("/")[2] if url.count("/") >= 2 else "-"


def _source_id(value) -> str:
    return value[0] if isinstance(value[0], str) else value[0][1]


def build() -> str:
    verified = _load(TOOLS / "verified.json")
    seeds = _load(DEMO / "seed_dois.json")["papers"]
    selected = {s["doi"]: s for s in _load(TOOLS / "selected.json")}
    sources = _load(TOOLS / "sources.json")
    kept = {p["doi"] for p in seeds}
    passed = [r for r in verified if r["ok"]]
    rejected = [r for r in verified if not r["ok"]]
    not_selected = [r for r in passed if r["doi"] not in kept]
    pass1 = [r for r in verified if r.get("screening_pass") == 1]
    pass2 = [r for r in verified if r.get("screening_pass") == 2]
    only_browser = [r["doi"] for r in verified if r.get("ok_browser_ua") and not r["ok"]]
    journals = len({p["journal"] for p in seeds})
    years = sorted({p["year"] for p in seeds})
    source_line = ", ".join(f"{name} {_source_id(val)}" for name, val in sources.items())

    out: list[str] = []
    add = out.append
    add("# Seed-paper and claim sources for the reviewer demo\n")
    add(
        f"Access date: {ACCESS_DATE} (all API calls and PDF checks made on this date from "
        "Python `httpx`). This file is generated by `demo/tools/build_sources.py`; every "
        "count, table and list below is computed from the JSON audit files in `demo/tools/` "
        "(checked by `demo/tests/test_seed_contract.py`).\n"
    )
    add("## Query\n")
    add(
        "OpenAlex `GET https://api.openalex.org/works` with `search` = `\"written corrective "
        "feedback\"` and, in a second pass, `\"corrective feedback\" writing accuracy`; "
        "`filter` = `is_oa:true,type:article,publication_year:2015-2025,"
        f"primary_location.source.id:<{len(sources)} journal IDs>`; `per-page=200`, cursor "
        "paging, `mailto` = the OPENALEX_EMAIL configured for the backend. 446 unique works "
        "returned (`candidates_raw.json`).\n"
    )
    add(f"Journals ({len(sources)} journal source IDs): {source_line}.\n")
    add("## Screening of candidates\n")
    add(
        "Pass 1 kept a work when: the title contains 'feedback'; the title or abstract "
        "contains 'writ'; `best_oa_location.pdf_url` is present; the journal is not Frontiers "
        "in Psychology (excluded to keep the set within applied-linguistics venues). "
        f"{len(pass1)} candidates.\n"
    )
    add(
        "Pass 2 (added after the backend-client re-check below left only 10 "
        "usable papers) re-screened the remaining raw works with a purely lexical rule: the "
        "title mentions feedback, error correction or revision, `best_oa_location.pdf_url` "
        "is present and the journal is not Frontiers in Psychology. Topical fit with the "
        "written-feedback protocol was not judged at this stage but at selection time (see "
        f"'Verified but not selected'). {len(pass2)} candidates were added: "
        f"{', '.join(r['doi'] for r in pass2)}. {len(verified)} candidates in total "
        "(`candidates_filtered.json`, field `screening_pass`).\n"
    )
    add("## Open-access verification\n")
    add(
        "Route (`verify_pdf.py`): Unpaywall `GET https://api.unpaywall.org/v2/<doi>?email="
        "<UNPAYWALL_EMAIL>` (the address is read from the environment or the repository "
        "`.env`; it is not stored in the package). Only `best_oa_location.url_for_pdf` is "
        "used; when Unpaywall returns no PDF URL the script falls back to the single OpenAlex "
        "`best_oa_location.pdf_url` carried in the candidate record. No other `oa_locations` "
        "are tried.\n"
    )
    add(
        "The PDF check uses a client equivalent to the backend's `fetch_pdf_from_url` "
        "(`backend/app/services/fulltext.py`): `httpx.Client(timeout=30.0, "
        "follow_redirects=True)` with httpx's default User-Agent and no extra headers. A URL "
        "passes when the response is HTTP 200 with `content-type: application/pdf` and a body "
        "beginning with `%PDF`. This is what the product itself observes during full-text "
        "acquisition, so `pdf_http_status` and `pdf_content_type` in `seed_dois.json` "
        "describe the pathway the demo reproduces. (An earlier verification pass "
        "used a Chrome-like User-Agent, which the backend does not send.)\n"
    )
    add(
        f"Result: {len(passed)} of {len(verified)} passed the PDF check; {len(rejected)} were "
        f"rejected. All {len(passed)} passing papers were found through Unpaywall "
        "(`oa_verified_via` = `unpaywall`). With `--browser-ua` the script also records what "
        f"a browser User-Agent would get: {len(only_browser)} candidates (all hosted on "
        "scholarspace.manoa.hawaii.edu, Language Learning & Technology) return a PDF only to "
        "a browser User-Agent and HTTP 403 to the backend client; they are rejected and none "
        "of them is a seed.\n"
    )
    add(f"## Verified and kept ({len(seeds)})\n")
    add(
        f"{len(seeds)} of the {len(passed)} passing papers were kept for journal/year spread: "
        f"{journals} journals, {years[0]}-{years[-1]}. First-author names are from Crossref "
        "(`selected.json`, `authors_crossref`); `citation_key` is the `surname_year` key the "
        "backend derives for the paper (last token of the first author's name + year).\n"
    )
    add("| DOI | Year | Journal | First author (key) | PDF host | Version | Licence |")
    add("|---|---|---|---|---|---|---|")
    for p in seeds:
        r = selected[p["doi"]]
        up = r.get("unpaywall") or {}
        add(
            f"| {p['doi']} | {p['year']} | {p['journal']} | {r['authors_crossref'][0]} "
            f"({r['citation_key']}) | {_host(r)} | {up.get('version')} | "
            f"{up.get('license') or 'not stated'} |"
        )
    add("")
    add(f"## Verified but not selected ({len(not_selected)})\n")
    add("Passed the PDF check but left out, with the reason:\n")
    for r in not_selected:
        add(
            f"- {r['doi']} ({r['year']}, {r['journal']}): {r['title']} - "
            f"{NOT_SELECTED_REASONS.get(r['doi'], 'left out')}"
        )
    add("")
    add(f"## Rejected ({len(rejected)})\n")
    add(
        "PDF not retrievable by the backend-equivalent client on the access date (HTML "
        "challenge page, 403, 202, timeout or connection error):\n"
    )
    for r in rejected:
        h = r["http"]
        extra = " (200 application/pdf to a browser User-Agent)" if r.get("ok_browser_ua") else ""
        add(f"- {r['doi']} ({r['year']}, {r['journal']}): HTTP {h['status']} {h['ctype']} "
            f"from {_host(r)}{extra}")
    add("")
    add("## Claim construction\n")
    add(
        "Source paper: Mao, Z., Lee, I., & Li, S. (2024). Written corrective feedback in "
        "second language writing: A synthesis of naturalistic classroom studies. *Language "
        "Teaching*, 57(1). https://doi.org/10.1017/S0261444823000393 - published version "
        "(CC BY) from the Cambridge Core PDF recorded in `seed_dois.json`, text extracted with "
        "`pymupdf` (the library the backend uses). The paper was chosen because the backend "
        "claim extractor only parses citations of the form `(Surname, YEAR)` / `(Surname et "
        "al., YEAR)` with a single ASCII capitalised surname and keys papers as `surname_year` "
        "from the first author's last-name token; `Mao` + `2024` gives `mao_2024`, which no "
        "other seed shares. Both claims are built from the abstract sentence quoted in "
        "`protocol.json` -> `claims[].construction` (\"A systematic search generated 50 "
        "empirical studies ... four major themes ...\") together with the abstract's "
        "description of the corpus as naturalistic studies in which feedback is not "
        "manipulated: `supported-1` paraphrases them; `unsupported-1` reverses the study "
        "design (experimental, manipulated feedback) and the number of themes (two).\n"
    )
    add(
        "The previous claim source (Bonilla López et al., 2018, 10.1111/lang.12295) stays in "
        "the library as a seed but is not cited by a claim: its first-author key is "
        "`lópez_2018`, which the backend regex cannot produce from any ASCII citation.\n"
    )
    add("## Files in demo/tools/\n")
    add(
        "`verify_pdf.py` is the verification script (`python demo/tools/verify_pdf.py "
        "candidates_filtered.json verified.json --browser-ua`); it prints the counts used "
        "above. `build_sources.py` regenerates this file. `sources.json`, "
        "`candidates_raw.json`, `candidates_filtered.json`, `verified.json`, `selected.json` "
        "are the inputs/outputs kept for audit. The downloaded PDF and its text are not "
        "committed."
    )
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    (DEMO / "SOURCES.md").write_text(build(), encoding="utf-8")
    print(f"wrote {DEMO / 'SOURCES.md'}")
